### ISSUE TITLE
No module named 'pyemma._base.fixed_seed'

### ISSUE THREAD

**Issue by rafwiewiora** [markovmodel/feature_selection#1]
Hi!

Just started playing with the code (on chignolin-xyz first), I'm hitting:

```
Traceback (most recent call last):
  File "calc_cov_single_feat.py", line 101, in <module>
    run(args.id_)
  File "calc_cov_single_feat.py", line 85, in run
    cov = e.estimate_covs(test_system=test_system, feature=feature, lag=lag, n_covs=50)
  File "/lila/home/rafal.wiewiora/repos/feature_selection/scripts/estimate.py", line 26, in estimate_covs
    from covariances import Covariances
  File "/lila/home/rafal.wiewiora/repos/feature_selection/scripts/covariances.py", line 8, in <module>
    from pyemma._base.fixed_seed import FixedSeedMixIn
ModuleNotFoundError: No module named 'pyemma._base.fixed_seed'
```

indeed I don't find this module even in `devel`. 

Extremely naively I've quickly tried removing that import and changing 
`class Covariances(StreamingEstimator, SerializableMixIn, FixedSeedMixIn)` 
to 
`class Covariances(StreamingEstimator, SerializableMixIn)`

which fails with:
```
Traceback (most recent call last):
  File "calc_cov_single_feat.py", line 101, in <module>
    run(args.id_)
  File "calc_cov_single_feat.py", line 85, in run
    cov = e.estimate_covs(test_system=test_system, feature=feature, lag=lag, n_covs=50)
  File "/lila/home/rafal.wiewiora/repos/feature_selection/scripts/estimate.py", line 28, in estimate_covs
    cov.estimate(reader)
  File "/home/rafal.wiewiora/anaconda3/envs/clean/lib/python3.7/site-packages/pyemma/coordinates/data/_base/streaming_estimator.py", line 44, in estimate
    super(StreamingEstimator, self).estimate(X, **kwargs)
  File "/home/rafal.wiewiora/anaconda3/envs/clean/lib/python3.7/site-packages/pyemma/_base/estimator.py", line 407, in estimate
    self._model = self._estimate(X)
  File "/lila/home/rafal.wiewiora/repos/feature_selection/scripts/covariances.py", line 141, in _estimate
    for X, Y in splitter.split(iterable):
  File "/lila/home/rafal.wiewiora/repos/feature_selection/scripts/covariances.py", line 104, in split
    for first_chunk, lagged_chunk in it:
TypeError: 'NoneType' object is not iterable
```

**Comment by jchodera** [comment]
@marscher @brookehus did you folks ever manage to make this package installable and runnable?

**Comment by marscher** [comment]
It is only intended to be a collection of scripts to perform the feature selection task on our cluster system. The second stack trace indicates, that the passed reader is simply None. That might be due to the fact that reader creation is tightly coupled to our clusters filesystem layout.

The scoring is already implemented in PyEMMA, we could think about eventually integrating the whole CV pipeline.

**Comment by rafwiewiora** [comment]
We just need working scripts to reproduce your paper. Not sure what you're saying -- these still don't work, there's still the `No module named 'pyemma._base.fixed_seed'` in 2.5.7. Are you saying my solution was right, I just need to work out that reader creation thing?

**Comment by marscher** [comment]
Yes, your solution is right and you need to create the readers properly.

**Comment by rafwiewiora** [comment]
awesome, thanks!!
